"""Seed the "Nimbus Retail Systems" demo tenant with the 8 persona users.

Mirrors docs/data-model/demo-dataset-spec.md §8. Phase 1 seeds only the tenant + users/roles
(enough to log in as every persona and exercise RBAC). The full financial/graph dataset is
generated by the Phase 2 seeder in ``packages/database``.
"""

from __future__ import annotations

from typing import List, Tuple

from ..core.rbac import Role
from ..core.security import hash_password
from ..repositories.memory import InMemoryStore, StoredCompany, StoredUser

DEMO_SLUG = "nimbus"

# (full_name, email, title, role)
_DEMO_USERS: List[Tuple[str, str, str, str]] = [
    ("Dana Reyes", "ceo@nimbus.test", "Chief Executive Officer", Role.CEO),
    ("Marcus Lin", "cfo@nimbus.test", "Chief Financial Officer", Role.CFO),
    ("Priya Anand", "coo@nimbus.test", "Chief Operating Officer", Role.COO),
    ("Sofia Marin", "strategy@nimbus.test", "Chief Strategy Officer", Role.STRATEGY),
    ("Tom Becker", "analyst@nimbus.test", "Finance Analyst", Role.ANALYST),
    ("Wei Zhang", "ops@nimbus.test", "Operations Manager", Role.OPS_MANAGER),
    ("Aisha Khan", "depthead@nimbus.test", "Head of Sales", Role.DEPT_HEAD),
    ("Nimbus Admin", "admin@nimbus.test", "System Administrator", Role.ADMIN),
]


def seed_demo(store: InMemoryStore, password: str, *, force: bool = False) -> List[Tuple[str, str]]:
    """Idempotently seed the demo tenant. Returns the list of (email, role) logins."""
    existing = next(
        (c for c in store._companies.values() if c.slug == DEMO_SLUG), None  # noqa: SLF001
    )
    if existing and not force:
        return [(email, role) for _, email, _, role in _DEMO_USERS]
    if force:
        store.reset()

    company = store.add_company(
        StoredCompany(
            name="Nimbus Retail Systems",
            slug=DEMO_SLUG,
            industry="Omnichannel retail & B2B wholesale",
            base_currency="USD",
        )
    )

    pw_hash = hash_password(password)
    logins: List[Tuple[str, str]] = []
    for full_name, email, title, role in _DEMO_USERS:
        store.add_user(
            StoredUser(
                company_id=company.id,
                email=email,
                full_name=full_name,
                title=title,
                password_hash=pw_hash,
                roles=[role],
            )
        )
        logins.append((email, role))
    return logins
